name: PickyPal
description: >-
  Yippieh, it's here! The scanner, which shows u, if your food is good or not for your allergies and other food preferences!
homepage: https://jakob-jung.com
funding: 
- https://ko-fi.com/bloedboemmel
issue_tracker: https://github.com/bloedboemmel/PickyPal/issues
documentation: https://github.com/bloedboemmel/PickyPal
repository: https://github.com/bloedboemmel/PickyPal
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.7+0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  qr_mobile_vision:
    git:
      url: https://github.com/rmtmckenzie/flutter_qr_mobile_vision
      ref: master
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  provider: ^6.1.2
  fl_chart: ^0.69.0
  settings_ui: 2.0.2
  url_launcher: ^6.3.0
  numberpicker: ^2.1.2
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  visibility_detector: ^0.4.0+2



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: FoodIcons
      fonts:
        - asset: lib/assets/fonts/FoodIcons.ttf
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo.png"
  min_sdk_android: 21

