name: PickyPal
description: >-
  Yippieh, it's here! The scanner, which shows u, if your food is good or not for your allergies and other food preferences!
homepage: https://jakob-jung.com
funding: -https://ko-fi.com/bloedboemmel
issue_tracker: https://github.com/bloedboemmel/PickyPal/issues
documentation: https://github.com/bloedboemmel/PickyPal
repository: https://github.com/bloedboemmel/PickyPal
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+7

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  http: 0.13.5
  shared_preferences: ^2.0.5
  qr_mobile_vision:
    git:
      url: https://github.com/ADDInformatique/flutter_qr_mobile_vision
      ref: master
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"
  provider: ^6.0.1
  fl_chart: ^0.61.0
  settings_ui: 2.0.2
  url_launcher: ^6.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: FoodIcons
      fonts:
        - asset: lib/assets/fonts/FoodIcons.ttf
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo.png"
  min_sdk_android: 21

