name: PickyPal
description: >-
  Yippieh, it's here! The scanner, which shows u, if your food is good or not for your allergies!
homepage: https://jakob-jung.com
funding: -https://ko-fi.com/bloedboemmel
issue_tracker: https://github.com/IsItFree/is_it_free_flutter/issues
documentation: https://github.com/IsItFree/is_it_free_flutter
repository: https://github.com/IsItFree/is_it_free_flutter
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: 0.13.5
  shared_preferences: ^2.0.5
  qr_mobile_vision:
    git:
      url: https://github.com/ADDInformatique/flutter_qr_mobile_vision
      ref: master
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"
  provider: ^6.0.1
  fl_chart: ^0.61.0

flutter:
  uses-material-design: true
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo.jpg"
  min_sdk_android: 21

