// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIjUcpWkZeTol9RfWr33E2Gi9ke4nFanc',
    appId: '1:129943256555:web:38234b2765b30cd6f7adae',
    messagingSenderId: '129943256555',
    projectId: 'pickypal-ddcca',
    authDomain: 'pickypal-ddcca.firebaseapp.com',
    storageBucket: 'pickypal-ddcca.appspot.com',
    measurementId: 'G-G4MR4FFC3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs-uMj6pY1iZzPjlkQc3cLrEyLooR1ryg',
    appId: '1:129943256555:android:1de1f6b1c7828448f7adae',
    messagingSenderId: '129943256555',
    projectId: 'pickypal-ddcca',
    storageBucket: 'pickypal-ddcca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcihGQjSgiH6kfZ9RV45qBiZH6oo4PHAI',
    appId: '1:129943256555:ios:20ad218ce28d2b89f7adae',
    messagingSenderId: '129943256555',
    projectId: 'pickypal-ddcca',
    storageBucket: 'pickypal-ddcca.appspot.com',
    iosClientId: '129943256555-cicq9gtnqa7pqruigf292ji0arpsbq5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBarcode3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcihGQjSgiH6kfZ9RV45qBiZH6oo4PHAI',
    appId: '1:129943256555:ios:20ad218ce28d2b89f7adae',
    messagingSenderId: '129943256555',
    projectId: 'pickypal-ddcca',
    storageBucket: 'pickypal-ddcca.appspot.com',
    iosClientId: '129943256555-cicq9gtnqa7pqruigf292ji0arpsbq5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBarcode3',
  );
}
