/// Flutter icons FoodIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FoodIcons
///      fonts:
///       - asset: fonts/FoodIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FoodIcons {
  FoodIcons._();

  static const _kFontFam = 'FoodIcons';
  static const String? _kFontPkg = null;

  static const IconData vegeterian = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gluten = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData milk = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nut = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData palm = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carbs = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soy = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glutamate = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vegan = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
